CREATE TABLE IF NOT EXISTS USER_INFO(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
TELEGRAMID TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS USERS_TABLE (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
USERNAME TEXT,
FOREIGN KEY (USERNAME) REFERENCES USERS_INFO (TELEGRAMID)
);

CREATE TABLE IF NOT EXISTS FACULTY (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
FACULTY_NAME TEXT,
USERNAME TEXT,
FOREIGN KEY (USERNAME) REFERENCES USERS_INFO (TELEGRAMID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WEEK(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
CHET INTEGER,
NUMOFWEEK INTEGER,
USERNAME TEXT,
FACULTY TEXT,
FOREIGN KEY (FACULTY) REFERENCES FACULTY (FACULTY)
FOREIGN KEY (USERNAME) REFERENCES USERS_INFO (TELEGRAMID)
);

CREATE TABLE IF NOT EXISTS DAYWEEK(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
DATE TEXT UNIQUE NOT NULL,
NUMOFWEEK INTEGER,
USERNAME TEXT,
FACULTY TEXT,
DAYOFWEEK TEXT,
FOREIGN KEY (USERNAME) REFERENCES USERS_INFO (TELEGRAMID),
FOREIGN KEY (NUMOFWEEK) REFERENCES WEEK (NUMOFWEEK),
FOREIGN KEY (FACULTY) REFERENCES FACULTY (FACULTY_NAME)
);

CREATE TABLE IF NOT EXISTS SUBJECT (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
DATE1 TEXT,
DAY_WEEK text,
SUBJECT_name TEXT NOT NULL, 
TIME1 TEXT,
FACULTY TEXT,
USERNAME TEXT,
FOREIGN KEY (USERNAME) REFERENCES USERS_INFO (TELEGRAMID),
FOREIGN KEY (DATE1) REFERENCES DAYWEEK (DATE)
);


CREATE TABLE IF NOT EXISTS TASK(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
DATE TEXT UNIQUE NOT NULL,
FACULTY TEXT,
TIME TEXT,
TASK_name TEXT,
FLAG TEXT,
USERNAME TEXT,
FOREIGN KEY (USERNAME) REFERENCES USERS_INFO (TELEGRAMID),
FOREIGN KEY (DATE,TIME) REFERENCES SUBJECT (DATE,TIME)
);
